name: Build Emscripten Desktop Apps

on:
  push:
    paths:
      - 'desktop/**'
      - '.github/workflows/build_emscripten.yml'
  pull_request:
    paths:
      - 'desktop/**'
      - '.github/workflows/build_emscripten.yml'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Need full git history for version info

      - name: Build Emscripten Apps
        working-directory: desktop
        run: |
          chmod +x build_emscripten.sh
          ./build_emscripten.sh

      - name: Upload Emscripten builds
        uses: actions/upload-artifact@v4
        with:
          name: emscripten-builds
          path: |
            desktop/*.html
            desktop/*.js
            desktop/*.wasm
          if-no-files-found: error

  upload-to-release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download emscripten builds
        uses: actions/download-artifact@v4
        with:
          name: emscripten-builds
          path: emscripten-builds

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            emscripten-builds/*.html
            emscripten-builds/*.js
            emscripten-builds/*.wasm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 