name: Build Firmware

on:
  push:
    paths:
      - 'firmware/**'
      - '.github/workflows/build_firmware.yml'
  pull_request:
    paths:
      - 'firmware/**'
      - '.github/workflows/build_firmware.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate version info
        id: version
        run: |
          # Get version from the latest tag, fallback to 0.0.0 if no tag
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          
          # Short commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)

          # GitHub build number
          BUILD_NUMBER=${GITHUB_RUN_NUMBER}

          # Composite version string
          FULL_VERSION="${VERSION}+build${BUILD_NUMBER}-${COMMIT_HASH}"

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV

      - name: Write version to header
        run: |
          cat <<EOF > firmware/src/version.h
          #pragma once
          #define FIRMWARE_VERSION         "${VERSION}"
          #define FIRMWARE_COMMIT_HASH     "${COMMIT_HASH}"
          #define FIRMWARE_BUILD_NUM       "${BUILD_NUMBER}"
          #define FIRMWARE_VERSION_STRING  "${FULL_VERSION}"
          EOF

      - name: Echo version info
        run: |
          cat firmware/src/version.h

      - name: Create version JSON file
        run: |
          cat <<EOF > firmware/version.json
          {
            "version": "$VERSION",
            "commit_hash": "$COMMIT_HASH",
            "build_number": "$BUILD_NUMBER",
            "full_version": "$FULL_VERSION"
          }
          EOF

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run --project-dir firmware
        
      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-rainbow-firmware
          path: |
            firmware/.pio/build/atomic14-esp32-rainbow-01/bootloader.bin
            firmware/.pio/build/atomic14-esp32-rainbow-01/firmware.bin
            firmware/.pio/build/atomic14-esp32-rainbow-01/partitions.bin
            firmware/version.json
          if-no-files-found: error
