name: Build Emscripten Desktop Apps

on:
  push:
    paths:
      - 'desktop/**'
      - '.github/workflows/build_emscripten.yml'
  pull_request:
    paths:
      - 'desktop/**'
      - '.github/workflows/build_emscripten.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Need full git history for version info

      - name: Build Emscripten Apps
        working-directory: desktop
        run: |
          chmod +x build_emscripten.sh
          ./build_emscripten.sh

      - name: Upload Emscripten builds
        uses: actions/upload-artifact@v4
        with:
          name: emscripten-builds
          path: |
            desktop/*.html
            desktop/*.js
            desktop/*.wasm
          if-no-files-found: error 